// <auto-generated />
using DbClinic.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbClinic.Migrations
{
    [DbContext(typeof(PersonDb))]
    [Migration("20230513024329_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbClinic.DataBase.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AnamnesisDesise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnamnesisLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ObjectStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PersonalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanSurvey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanTherapy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recomendation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
